# Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # Install dependencies needed for running tests
      - npm ci

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
      - npm test
  post_build:
    commands:
      # Leave only runtime dependencies
      - npm prune --production
artifacts:
  type: zip
  files:
    - README.md
    - package.json
    - app.js
    - appspec.yml
    - scripts/*
    - node_modules/**/*
    - public/**/*